In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [4]:
df = pd.read_csv("Salary Data.csv")
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  373 non-null    float64
 1   Gender               373 non-null    object
 2   Education Level      373 non-null    object
 3   Job Title            373 non-null    object
 4   Years of Experience  373 non-null    float64
 5   Salary               373 non-null    float64
dtypes: float64(3), object(3)
memory usage: 17.7+ KB

In [7]:
df.isnull().sum()

Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

In [9]:
df.describe()

              Age  Years of Experience         Salary
count  373.000000           373.000000     373.000000
mean    37.431635            10.030831  100577.345845
std      7.069073             6.557007   48240.013482
min     23.000000             0.000000     350.000000
25%     31.000000             4.000000   55000.000000
50%     36.000000             9.000000   95000.000000
75%     44.000000            15.000000  140000.000000
max     53.000000            25.000000  250000.000000

In [24]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df = df.fillna(df.mean(numeric_only=True))
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Education Level'] = df['Education Level'].fillna(df['Education Level'].mode()[0])
df['Job Title'] = df['Job Title'].fillna(df['Job Title'].mode()[0])

In [25]:
df.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [35]:
X=df.drop(columns=['Education Level','Salary'])
y=df['Salary']
X['Gender'] = X['Gender'].map({'Male':1,'Female':0})
X=pd.get_dummies(X,columns=['Job Title'],dtype=int)

In [36]:
X.head()

,Age,Gender,Years of Experience,Job Title_Account Manager,Job Title_Accountant,Job Title_Administrative Assistant,Job Title_Business Analyst,Job Title_Business Development Manager,Job Title_Business Intelligence Analyst,Job Title_CEO,...,Job Title_Supply Chain Manager,Job Title_Technical Recruiter,Job Title_Technical Support Specialist,Job Title_Technical Writer,Job Title_Training Specialist,Job Title_UX Designer,Job Title_UX Researcher,Job Title_VP of Finance,Job Title_VP of Operations,Job Title_Web Developer
0,32.0,1,5.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,28.0,0,3.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,45.0,1,15.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,36.0,0,7.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,52.0,1,20.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [37]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.3,random_state=42)

In [38]:
X_train.head()

,Age,Gender,Years of Experience,Job Title_Account Manager,Job Title_Accountant,Job Title_Administrative Assistant,Job Title_Business Analyst,Job Title_Business Development Manager,Job Title_Business Intelligence Analyst,Job Title_CEO,...,Job Title_Supply Chain Manager,Job Title_Technical Recruiter,Job Title_Technical Support Specialist,Job Title_Technical Writer,Job Title_Training Specialist,Job Title_UX Designer,Job Title_UX Researcher,Job Title_VP of Finance,Job Title_VP of Operations,Job Title_Web Developer
19,51.0,1,22.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
324,29.0,0,2.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
79,30.0,0,3.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
168,31.0,0,4.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,25.0,0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [39]:
X_test.head()

,Age,Gender,Years of Experience,Job Title_Account Manager,Job Title_Accountant,Job Title_Administrative Assistant,Job Title_Business Analyst,Job Title_Business Development Manager,Job Title_Business Intelligence Analyst,Job Title_CEO,...,Job Title_Supply Chain Manager,Job Title_Technical Recruiter,Job Title_Technical Support Specialist,Job Title_Technical Writer,Job Title_Training Specialist,Job Title_UX Designer,Job Title_UX Researcher,Job Title_VP of Finance,Job Title_VP of Operations,Job Title_Web Developer
167,46.0,1,18.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,39.0,0,10.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,44.0,1,16.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
316,34.0,0,6.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57,43.0,1,17.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [41]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [46]:
y_pred = model.predict(X_test)

In [47]:
y_pred

array([134675.46415731, 100100.37045819, 125744.7229864 , 100000.        ,
       127953.13529142, 175005.10915563, 152556.33834343, 120102.80750193,
        42220.32078664,  94506.52073252, 126059.1143415 , 148071.57591367,
        46975.24444198,  66514.60175248,  56686.40677037, 152205.51570886,
        75497.16740618,  58195.04349108,  96264.30290145,  88893.27916255,
       116663.10855476, 112133.10474324, 126873.20212661,  51170.45380186,
       101158.24130392,  60510.35642685, 142477.726188  , 129739.88620257,
       158129.8757687 , 161560.45142386,  64328.85979915, 114097.50557822,
        66566.42623527, 140073.19924049,  91545.32020823,  28223.78799086,
       172275.41035571,  63229.53479003,  58715.61822918,  51484.62431417,
        43341.25019953,  89990.30407785, 162547.62083485, 171595.20818857,
        60972.5765096 , 143474.72391179, 100032.43263848,  59863.4892137 ,
        46663.10855476,  60991.96835391, 100049.52438897, 105410.77587736,
        87305.2820655 ,  91128.47914021, 176595.17073505,  57034.4647531 ,
       177386.60308653,  61246.91976246,  66585.81807958,  91691.72505927,
       107902.63248889, 138291.26978609, 143625.59717252,  75497.16740618,
        45128.54819801,  60972.5765096 ,  48321.85835523, 119070.94009592,
        43341.25019953,  50913.35619848,  85525.91190596, 109534.28681873,
       152224.90755317, 149247.68057319, 105550.81140635, 108963.65402599,
       113247.60495409,  62120.44749412,  60062.99517478,  83318.82128118,
       138012.35560255,  95544.99973395,  44187.74882521,  96480.03470645,
       117913.30682461, 122251.72777528, 101604.54051935, 100452.68174983,
       118266.99679839, 120170.26510504,  58400.47051066, 183955.24217084,
       196673.78289048,  37968.32246018, 121128.47914021, 123507.63676688,
       124930.63520128, 106754.76150436, 111239.52393413, 112348.61123003,
        58195.04349108,  48915.7080809 ,  48341.25019953,    350.        ,
        44718.28616155,  42220.32078664, 136883.87646233,  87305.2820655 ,
       107667.73415779,  58989.96148203, 105518.72457367, 129433.92572328,
        47787.22894068])

In [48]:
y_test

167    150000.0
33      65000.0
15     125000.0
316     80000.0
57     140000.0
         ...
305     95000.0
244     70000.0
272     90000.0
173    140000.0
351     55000.0
Name: Salary, Length: 113, dtype: float64

In [49]:
from sklearn.metrics import r2_score

In [55]:
r2 =r2_score(y_test,y_pred)
print(r2)
n=X_test.shape[0]
p=X_test.shape[1]

adjusted_r2 = 1-((1-r2)*(n-1)/(n-p-1))
print(adjusted_r2)

0.8372026009102551
1.2805124415084834

In [57]:

print(X_train.shape)
print(X_test.shape)

(262, 177)
(113, 177)

In [58]:
print(df['Job Title'].nunique())

174