In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("Salary Data.csv")
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  373 non-null    float64
 1   Gender               373 non-null    object
 2   Education Level      373 non-null    object
 3   Job Title            373 non-null    object
 4   Years of Experience  373 non-null    float64
 5   Salary               373 non-null    float64
dtypes: float64(3), object(3)
memory usage: 17.7+ KB

In [4]:
df.isnull().sum()

Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

In [5]:
df.describe()

              Age  Years of Experience         Salary
count  373.000000           373.000000     373.000000
mean    37.431635            10.030831  100577.345845
std      7.069073             6.557007   48240.013482
min     23.000000             0.000000     350.000000
25%     31.000000             4.000000   55000.000000
50%     36.000000             9.000000   95000.000000
75%     44.000000            15.000000  140000.000000
max     53.000000            25.000000  250000.000000

In [6]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df = df.fillna(df.mean(numeric_only=True))
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Education Level'] = df['Education Level'].fillna(df['Education Level'].mode()[0])
df['Job Title'] = df['Job Title'].fillna(df['Job Title'].mode()[0])

In [7]:
df = pd.get_dummies(df, columns=["Education Level"],drop_first=True,dtype=int)
df = pd.get_dummies(df, columns=["Job Title"],drop_first=True,dtype=int)
df = pd.get_dummies(df, columns=['Gender'],drop_first=True,dtype=int)

In [8]:
df.isnull().sum()

Age                           0
Years of Experience           0
Salary                        0
Education Level_Master's      0
Education Level_PhD           0
                             ..
Job Title_UX Researcher       0
Job Title_VP of Finance       0
Job Title_VP of Operations    0
Job Title_Web Developer       0
Gender_Male                   0
Length: 179, dtype: int64

In [9]:

df.head()

,Age,Years of Experience,Salary,Education Level_Master's,Education Level_PhD,Job Title_Accountant,Job Title_Administrative Assistant,Job Title_Business Analyst,Job Title_Business Development Manager,Job Title_Business Intelligence Analyst,...,Job Title_Technical Recruiter,Job Title_Technical Support Specialist,Job Title_Technical Writer,Job Title_Training Specialist,Job Title_UX Designer,Job Title_UX Researcher,Job Title_VP of Finance,Job Title_VP of Operations,Job Title_Web Developer,Gender_Male
0,32.0,5.0,90000.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,28.0,3.0,65000.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,45.0,15.0,150000.0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,36.0,7.0,60000.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,52.0,20.0,200000.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [10]:
X=df.drop(columns='Salary')
y=df['Salary']

In [11]:
df.head()

,Age,Years of Experience,Salary,Education Level_Master's,Education Level_PhD,Job Title_Accountant,Job Title_Administrative Assistant,Job Title_Business Analyst,Job Title_Business Development Manager,Job Title_Business Intelligence Analyst,...,Job Title_Technical Recruiter,Job Title_Technical Support Specialist,Job Title_Technical Writer,Job Title_Training Specialist,Job Title_UX Designer,Job Title_UX Researcher,Job Title_VP of Finance,Job Title_VP of Operations,Job Title_Web Developer,Gender_Male
0,32.0,5.0,90000.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,28.0,3.0,65000.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,45.0,15.0,150000.0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,36.0,7.0,60000.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,52.0,20.0,200000.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [12]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.3,random_state=42)

In [13]:
X_train.head()

,Age,Years of Experience,Education Level_Master's,Education Level_PhD,Job Title_Accountant,Job Title_Administrative Assistant,Job Title_Business Analyst,Job Title_Business Development Manager,Job Title_Business Intelligence Analyst,Job Title_CEO,...,Job Title_Technical Recruiter,Job Title_Technical Support Specialist,Job Title_Technical Writer,Job Title_Training Specialist,Job Title_UX Designer,Job Title_UX Researcher,Job Title_VP of Finance,Job Title_VP of Operations,Job Title_Web Developer,Gender_Male
19,51.0,22.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
324,29.0,2.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
79,30.0,3.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
168,31.0,4.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,25.0,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
X_test.head()

,Age,Years of Experience,Education Level_Master's,Education Level_PhD,Job Title_Accountant,Job Title_Administrative Assistant,Job Title_Business Analyst,Job Title_Business Development Manager,Job Title_Business Intelligence Analyst,Job Title_CEO,...,Job Title_Technical Recruiter,Job Title_Technical Support Specialist,Job Title_Technical Writer,Job Title_Training Specialist,Job Title_UX Designer,Job Title_UX Researcher,Job Title_VP of Finance,Job Title_VP of Operations,Job Title_Web Developer,Gender_Male
167,46.0,18.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
33,39.0,10.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,44.0,16.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
316,34.0,6.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57,43.0,17.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [16]:
scaler = StandardScaler()
X_train_scaled =  scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [21]:
model = LinearRegression()
model.fit(X_train_scaled,y_train)

LinearRegression()

In [22]:
y_pred = model.predict(X_test_scaled)

In [23]:
y_pred

array([142886.52970038,  99707.17878906, 123252.71802328, 100000.        ,
       135335.09434967, 180303.46434522, 147258.27798794, 124184.29280622,
        43081.10348029,  98627.81027907, 135278.34496642, 143783.44477298,
        47310.97561503,  71227.43933624,  56644.97856675, 153097.36955523,
        76362.47417357,  63525.10765356,  96324.57714478,  93430.33206372,
       117616.49965045, 113804.63153445, 136396.88400089,  50662.08204519,
       100540.68653837,  59501.63732426, 149376.17539987, 128925.71843979,
       154279.42604801, 158528.49450691,  64073.58133794, 115713.24149397,
        68150.18347369, 146204.93563638,  95806.82150102,  26088.87947335,
       170182.80630415,  65766.68312414,  58876.10312259,  52071.97587581,
        43492.59375773,  90315.65606749, 155040.09117157, 173258.69795023,
        62321.39312337, 141622.0596151 , 108975.57724965,  64716.85782834,
        47616.49965045,  61690.08098839, 100250.59176775, 101503.77434341,
        86326.94755401,  91722.64500039, 175463.37713382,  57245.91131529,
       174434.70002803,  61592.51640092,  67518.87133871,  95841.98516136,
       110946.24632888, 138354.23135799, 143795.40912839,  76362.47417357,
        44924.07366996,  62321.39312337,  49123.90589271, 118485.71732418,
        43492.59375773,  52386.4574231 ,  78926.24599336, 108725.42498271,
       152466.05742025, 148851.56999974, 105238.85892049, 110561.72491684,
       111179.95389528,  63412.72598878,  59403.15760165,  86970.22957842,
       133848.50907271,  95343.20832302,  50696.71258655,  98040.90548386,
       113347.32553721, 119264.72480675, 100992.33536095, 101555.88760391,
       120298.06360063, 121542.03737831,  58427.529458  , 181212.34377323,
       201439.09983599,  37813.16006844, 121722.64500039, 123971.49383207,
       126883.60082915, 116527.01260036, 113329.74667844, 115683.7038138 ,
        63525.10765356,  49952.69624304,  48492.59375773,    350.        ,
        43865.68561426,  43081.10348029, 136875.28591266,  86326.94755401,
       104949.06434418,  58147.22640014, 104562.78840739, 127484.92718769,
        48230.05124265])

In [24]:
y_test

167    150000.0
33      65000.0
15     125000.0
316     80000.0
57     140000.0
         ...
305     95000.0
244     70000.0
272     90000.0
173    140000.0
351     55000.0
Name: Salary, Length: 113, dtype: float64

In [25]:
from sklearn.metrics import r2_score

In [27]:
r2_test =r2_score(y_test,y_pred)
print(r2_test)
n=X_test.shape[0]
p=X_test.shape[1]

adjusted_r2 = 1-((1-r2_test)*(n-1)/(n-p-1))
print(adjusted_r2)

0.8464433557023087
1.2605809721415369

In [84]:

print(X_train.shape)
print(X_test.shape)

(262, 178)
(113, 178)

In [28]:
#underfit & overfit
y_train_pred = model.predict(X_train_scaled)
train_r2 = r2_score(y_train, y_train_pred)
r2_test =r2_score(y_test,y_pred)
print(train_r2)
print(r2_test)

0.9858643490326157
0.8464433557023087

In [29]:
#Lasso Regression
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error

In [30]:
lasso_model = Lasso(alpha=0.5)
lasso_model.fit(X_train_scaled,y_train)
y_preds = lasso_model.predict(X_test_scaled)

C:\Users\Amey\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.038e+08, tolerance: 6.245e+07
  model = cd_fast.enet_coordinate_descent(

In [31]:
mse = mean_squared_error(y_test,y_preds)
print("MSE:", mse)

MSE: 327100935.9341471

In [32]:
from sklearn.linear_model import LassoCV
a=[0.001,0.1,1,2,5,10,20,30,40,50,100]
lasso_cv_model = LassoCV(
    alphas= a,
    cv=5,
    max_iter=10000,
    random_state=42
)

lasso_cv_model.fit(X_train_scaled,y_train)
print(lasso_cv_model.alpha_)
y_pred = lasso_cv_model.predict(X_test_scaled)
mse = mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
print(mse)
print(r2)

100.0
267506685.98323992
0.8745710971707432